### ISSUE TITLE
React-navigation. Screen freezes after change from a screen with ViroARSceneNavigator to a normal screen

### ISSUE THREAD

**Issue by chouji19** [ViroCommunity/viro#138]
# Requirements: 
Please go through this checklist before opening a new issue
  - [x] Review the [documentation](https://docs.viromedia.com/)
  - [x] Search for existing issues in: [viromedia/viro](https://github.com/viromedia/viro/issues) & [ViroCommunity/viro](https://github.com/ViroCommunity/viro/issues)
  - [x] Use the latest [ViroReact release](https://docs.viromedia.com/docs/releases)

## Environment
Please provide the following information about your environment:
1. Development OS: Mac OS Monterey 12.3.1
2. Device OS & Version: iOS 15.4.1 
3. Version: @viro-community/react-viro: 2.23.0  and React Native version 0.65.1 @react-navigation/native 6.0.10
4. Device(s): What device(s) are you are seeing the issue on IPhone 11
## Description

I have a react-navigation with two screens.

1. a screen with flatlist (No viro here)
2. a Viro Scene

When I navigate from flatlist to scene it works as expected
when I goBAck to the first screen the app freeze.

## Reproducible Demo

I have implemented a react-navigation I have one screen with a FlatList. It works normally when I start the app and I navigate to a new screen from the SceneCard component. it works as expected

`
	return (
		<SafeAreaView>
			<View style={styles.container}>
				<SearchBar searchText={searchText} setSearchText={setSearchText} />
				{scenesList.length > 0 ? (
					<FlatList
						showsVerticalScrollIndicator={false}
						data={scenesList}
						renderItem={({item}:any) => (<SceneCard scene={item} key={item.id} />)}
						keyExtractor={(item:any) => item.id ?? v4()}
						// onEndReached={onEndReached}
						onEndReachedThreshold={1 / 7}
						ListFooterComponent={
							<View style={{marginBottom: 100}}/>
						}
					/>
				) : (
					<Text>No Scenes Available</Text>
				)}
			</View>
			<MainMenu />
		</SafeAreaView>
	);
` 
Code to navigate to the SceneScreen
`
const goToScene = () => {
		selectScene(scene);
		navigation.navigate('SceneScreen');
	};
`
The scene screen looks like this (I have tried to unmount with useFocusEffect and useIsFocus

`
const SceneScreen = () => {
	const [shouldHide, setShouldHide] = useState(false);
	console.log({shouldHide});
	useFocusEffect(() => {
		setShouldHide(false)
		return () => {
			console.log({shouldHide});
			setShouldHide(true)
		}
	});
	return !shouldHide ? (
		<View style={styles.container}>
			{!shouldHide && <ViroARSceneNavigator
				autofocus={true}
				initialScene={{
					scene: PoralScene,
				}}
				style={{ flex: 1 }}
			/>}
			{/* <View style={{ marginBottom: 100 }} /> */}
			<Menu />
		</View>
	) : <View />;
};
`

My portalScene Component renders a ViroARScene and a ViroPortal

`
return (<ViroARScene onTrackingUpdated={onInitialized} >
		<ViroAmbientLight color="#FFFFFF" />
		{urlResource ? (
			<ViroPortalScene passable={true} dragType="FixedDistance" onDrag={() => { }}>
				<ViroPortal position={[0, 0, -0.5]} scale={[.1, .1, .1]}>
					<Viro3DObject source={require('../../res/portal_ship/portal_ship.vrx')}
						resources={[require('../../res/portal_ship/portal_ship_diffuse.png'),
						require('../../res/portal_ship/portal_ship_normal.png'),
						require('../../res/portal_ship/portal_ship_specular.png')]}
						type="VRX" />
				</ViroPortal>
				<Viro360Image
					// source={{ uri: 'https://picsum.photos/1920/960', scale: 0.2 }}
					source={{ uri: urlResource }}
				/>
			</ViroPortalScene>
		) : <></>
		}
	</ViroARScene>
	);
`

Now when I go back from the SceneScreen (I have tried navigation.goBack(), navigation.dispatch and navigation.reset and even adding timeout to the action) the Screen with the flatlist is freeze and I can't do anything else with my app until I restart. 

`const handleGoBack = () => {
		setTimeout(() => {
			navigation.reset({
				index: 0,
				routes: [
					{
						name: 'ScenesListScreen',
					},
				],
			});
		}, 500);

	}
`

have you seen this problem before (As far as I have read, the reset instead of goback should be enough. but it is still not working for me)

Thanks.
I really apreciate

**Comment by ViktorVojtek** [comment]
Hi @chouji19 try the following package. It solved some issues with freezing or laggy transitions between screens.

https://github.com/nandorojo/react-navigation-heavy-screen

If this wont help check your android studio or xcode runtime logs for any information...

**Comment by illi-homz** [comment]
> Hi @chouji19 try the following package. It solved some issues with freezing or laggy transitions between screens.
> 
> https://github.com/nandorojo/react-navigation-heavy-screen
> 
> If this wont help check your android studio or xcode runtime logs for any information...

this log i get in Android Studio after app crashing
my app is crashing, don't freeze

```
FATAL EXCEPTION: GLThread 53825
Process: com.zvet, PID: 23500
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.SurfaceHolder android.opengl.GLSurfaceView.getHolder()' on a null object reference
	at com.viro.core.ViroViewARCore$ViroARRenderer.onSurfaceChanged(ViroViewARCore.java:300)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)
```

**Comment by ViktorVojtek** [comment]
@illi-homz 

To avoid this error handle the navigation from/to your AR screen via navigation dispatch actions.
In my case I reset my AR stack with CommonAction.reset like this:

```
navigation.dispatch(
  CommonActions.reset({
    index: 0,
    routes: [
      {
        name: 'ARStack',
        params: {
          screen: 'AR',
          params: undefined,
        },
      },
    ],
  }),
);
```
You would also have to handle the native android back button behavior if you do not want to hide the native bottom navigation bar completely.
You could do it with custom android back button behaviour. Here is the article from [react-navigation](https://reactnavigation.org/docs/custom-android-back-button-handling/)

I am using the custom event listener on every screen I need to go from/to my AR screen and it works great.

This would definitely help.

**Comment by illi-homz** [comment]
@ViktorVojtek

**Comment by illi-homz** [comment]
@ViktorVojtek 

your advice doesn't work

```js
const goBack = useCallback(() => {
	let {index, routeNames, routes} = navigation.getState();
	routeNames = routeNames.filter(el => el !== 'AR');
	routes = routes.filter(
		({ name }) => name !== 'AR',
	);
	navigation.dispatch(
		CommonActions.reset({
			index,
			routeNames,
			routes,
		}),
	);
	return true;
}, []);

useBackHandler(goBack);
```
there is a transition to a step back, but the application crashes
if you conditionally draw the navigator on the AP screen and then hide it, the application still crashes

```tsx
{isShow && (
	<ViroARSceneNavigator
		initialScene={{
			scene: RenderScene,
		}}
		worldAlignment='Gravity'
		autofocus
		style={styles.arView}
		viroAppProps={{
			onObjPress: showRotationUI,
			onRef: r => {
				console.log('r', r);
			},
		}}
	/>
)}
```

**Comment by anxheloo** [comment]
Is there any solution yet for this problem , navigating back? I am still not able to find a solution
