### ISSUE TITLE
Error while starting my app - (library "libviro_renderer.so" not found)

### ISSUE THREAD

**Issue by fareed945** [ViroCommunity/viro#59]
# Requirements: 
Please go through this checklist before opening a new issue
  - [x] Review the [documentation](https://docs.viromedia.com/)
  - [x] Search for existing issues in: [viromedia/viro](https://github.com/viromedia/viro/issues) & [ViroCommunity/viro](https://github.com/ViroCommunity/viro/issues)
  - [x] Use the latest [ViroReact release](https://docs.viromedia.com/docs/releases)

## Environment
Please provide the following information about your environment:
1. Development OS:  Windows
2. Device OS & Version: Andoid API 30
3. Version: ViroReact version - 2.21.1 and React Native version  - 0.63.1
4. Device(s): What device(s) are you are seeing the issue on (i.e. iPhone X, Samsung Note 8, etc) PIXEL_3_XL emulator

## Description
I'm getting the following error when trying to start my app, even after following all the steps as mentioned in the starter kit.
E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.test.viro, PID: 4598
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libviro_renderer.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.viromedia.bridge.module.MaterialManager.<clinit>(MaterialManager.java:58)
        at com.viromedia.bridge.ReactViroPackage.createNativeModules(ReactViroPackage.java:111)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
        at java.lang.Thread.run(Thread.java:923).

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, screen capture, video recording. The more information you provide, the better we can support you.

**Comment by fareed945** [comment]
Found the issue, it doesn't work on my emulator but it works fine on the physical device.
